name: Update Daily Keys from Google Sheets # Tên workflow rõ ràng hơn

on:
  schedule:
    - cron: '0 * * * *'  # Chạy hàng giờ (hoặc điều chỉnh nếu cần: ví dụ '0 0 * * *' cho mỗi ngày một lần vào nửa đêm UTC)
  workflow_dispatch:   # Cho phép chạy thủ công từ GitHub UI

jobs:
  update_keys: # Đổi tên job để rõ ràng hơn
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch JSON data from Google Script
        id: fetch_data # ID cho bước này để tham chiếu sau
        run: |
          GOOGLE_SCRIPT_URL="https://script.google.com/macros/s/AKfycbyu54ooCKK9mM8T-2E-HVk5bTPX8H-OAOAtnjpAu8gTPebV4k7cqT1GjQFdI5Lesz4W/exec"
          OUTPUT_FILE="Keys.json" # Tên tệp đầu ra cuối cùng

          echo "Attempting to fetch data from Google Script..."
          # Sử dụng curl -f để thất bại nếu mã trạng thái HTTP không phải 2xx
          # --retry 5: Thử lại 5 lần nếu có lỗi kết nối tạm thời
          # --retry-delay 5: Đợi 5 giây giữa các lần thử lại
          # -o: Ghi đầu ra vào tệp
          # 2>&1: Chuyển hướng stderr sang stdout để ghi vào biến 'response'
          response=$(curl -f --retry 5 --retry-delay 5 -o "${OUTPUT_FILE}_temp" "${GOOGLE_SCRIPT_URL}" 2>&1)
          CURL_STATUS=$? # Lưu mã thoát của curl

          if [ ${CURL_STATUS} -ne 0 ]; then
            echo "::error::Curl failed with status ${CURL_STATUS}. Response: ${response}"
            exit 1 # Thoát với lỗi nếu curl thất bại
          fi

          echo "Curl successful. Checking temporary JSON file..."

          # Kiểm tra xem tệp tạm thời có tồn tại và không rỗng không
          if [ ! -s "${OUTPUT_FILE}_temp" ]; then
            echo "::error::Received empty or invalid data from Google Script. Output file is empty."
            rm -f "${OUTPUT_FILE}_temp" # Xóa tệp rỗng/hỏng
            exit 1 # Thoát với lỗi
          fi

          # Kiểm tra xem nội dung có phải là JSON hợp lệ không (sử dụng jq)
          # jq -e sẽ trả về mã thoát 0 nếu JSON hợp lệ và không rỗng, ngược lại sẽ là 1
          if ! jq -e . < "${OUTPUT_FILE}_temp" > /dev/null; then
            echo "::error::Received invalid JSON from Google Script. Please check script output."
            rm -f "${OUTPUT_FILE}_temp" # Xóa tệp hỏng
            exit 1 # Thoát với lỗi
          fi

          echo "JSON data successfully fetched and validated."

          # Di chuyển tệp tạm thời (đã được xác thực) sang tệp đích cuối cùng
          mv "${OUTPUT_FILE}_temp" "${OUTPUT_FILE}"

          # In ra nội dung của tệp cuối cùng để dễ gỡ lỗi trong logs
          echo "Content of ${OUTPUT_FILE}:"
          cat "${OUTPUT_FILE}"
          echo "::endgroup::" # Kết thúc nhóm log

      - name: Check for changes and Commit
        # Chỉ chạy bước này nếu bước 'fetch_data' thành công
        if: success()
        run: |
          TARGET_FILE="keys.json" # Tên tệp đích

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Kiểm tra xem tệp đích có tồn tại trong repo không
          if git ls-files --error-unmatch "${TARGET_FILE}" >/dev/null 2>&1; then
            # Tệp tồn tại, so sánh nội dung cũ và mới
            OLD_CONTENT=$(git show HEAD:"${TARGET_FILE}" 2>/dev/null || true) # Lấy nội dung từ HEAD
            NEW_CONTENT=$(cat "${TARGET_FILE}")

            if [ "$OLD_CONTENT" = "$NEW_CONTENT" ]; then
              echo "Content of ${TARGET_FILE} has not changed. Skipping commit."
              exit 0 # Không có gì để commit, thoát thành công
            else
              echo "Content of ${TARGET_FILE} has changed. Preparing commit."
            fi
          else
            # Tệp không tồn tại (lần đầu tiên), luôn commit
            echo "${TARGET_FILE} does not exist in the repository. Committing new file."
          fi

          # Thêm và commit các thay đổi
          git add "${TARGET_FILE}"
          git commit -m "Auto-update ${TARGET_FILE} from Google Sheets"
          
          # Push các thay đổi lên remote
          echo "Pushing changes to remote repository..."
          git push
          echo "Changes pushed successfully."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Cung cấp token để push
