name: Update Keys from Google Sheets
on:
  schedule:
    - cron: '0 * * * *'  # Chạy hàng giờ
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch data from Google Script
        run: |
          curl -o keys.json "https://script.google.com/macros/s/AKfycbyu54ooCKK9mM8T-2E-HVk5bTPX8H-OAOAtnjpAu8gTPebV4k7cqT1GjQFdI5Lesz4W/exec"
          # Kiểm tra dữ liệu
          cat keys.json

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add keys.json
          git commit -m "Auto-update keys from Google Sheets"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
